### ISSUE TITLE
How can I see the details in your reset function？

### ISSUE THREAD

**Issue by ZhengyeHan** [liuzuxin/DSRL#1]
May I know the details of your reset function？
![image](https://github.com/liuzuxin/DSRL/assets/111236370/b4a0cc63-26ce-4a77-80f3-4249ddae51b0)

**Comment by liuzuxin** [comment]
It depends on which environment you use. Note that our offline env is simply a wrapper to add some more functions for the datasets. If you want to know how to interact with the environment, such as the observation space, action space, and reset, you can refer to each environment's instruction and codebase, respectively:
https://github.com/PKU-Alignment/safety-gymnasium
https://github.com/liuzuxin/Bullet-Safety-Gym
https://github.com/HenryLHH/metadrive_clean
