### ISSUE TITLE
MetaDrive Docs

### ISSUE THREAD

**Issue by weakenleg** [liuzuxin/DSRL#4]
Hi, author

I am interested in metadrive env, but when I check the link of this env, it does not have docs, like action, obs. And it is used for FSRL, so I want to know can you provide more detailed info of it?

**Comment by liuzuxin** [comment]
I would suggest asking @HenryLHH in the MetaDrive env repo for this issue.

**Comment by HenryLHH** [comment]
Hi, for the metadrive environment, please refer to the [document](https://metadrive-simulator.readthedocs.io/en/latest/) for details.
