### ISSUE TITLE
Download dataset error

### ISSUE THREAD

**Issue by Chenrf1121** [liuzuxin/DSRL#8]
`python ./example/run_mujoco.py --task Goal2`
<img width="1559" alt="image" src="https://github.com/user-attachments/assets/28ac905f-3401-4a94-95b2-8563cdb01943">
<img width="528" alt="image" src="https://github.com/user-attachments/assets/a734f403-c15b-466c-9e95-aee797c05173">
How to address it?

**Comment by liuzuxin** [comment]
@Chenrf1121 thanks for catching this. Our server was down. Just fixed it.
