### ISSUE TITLE
How to save rendering video in mujoco environment

### ISSUE THREAD

**Issue by Chenrf1121** [liuzuxin/DSRL#9]
I check gymnasium document, they introduce `gymnasium.utils.save_video` to save video, but I fail to save video of `OfflinePointGoal1Gymnasium-v0`.
the example code is
<img width="646" alt="image" src="https://github.com/user-attachments/assets/23d25013-9c70-41f7-b7ea-9e6b87dac44d">
, how to save dsrl datasets rendering video?

**Comment by liuzuxin** [comment]
Have you tried to save video in the original [safety-gymnasium](https://safety-gymnasium.readthedocs.io/en/latest/) repo? Our environment is a wrapper for theirs, so if their original repo doesn't support save video in this way, ours also can not.
